## default connection pool
debug: true
spring:
  sql:
    init:
      platform: postgresql
      mode: always
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pgpwd
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  data:
    mongodb:
      uri: mongodb+srv://swethachauhan:<M1v0qoAZjiaJucfp>@cluster0.c86gnga.mongodb.net/?retryWrites=true&w=majority
      database: myFirstDatabase

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR